## code to prepare `l_psm_parameters` dataset goes here

df_life_table <- NeuroblastomaPSM::df_lifeTable_Jordan[, 1:2]
colnames(df_life_table) <- c("age", "probs")

l_psm_parameters <- list(
  age = 4,
  body_weight = 15,
  smr_EFS = 5.6,
  smr_PPS = 10.64,
  cure_threshold = 10,
  GD2_unit_mg = 20,
  GD2_dose_days = 5,
  GD2_unit_price = 8790.26,
  TT_unit_mg = 20,
  TT_dose_days = 14,
  TT_unit_price = 0.24,
  GD2_aEvents_names = c(
    "anemia",
    "leukopenia",
    "neutropenia",
    "thrombocytopenia",
    "fever",
    "urticaria",
    "immunotherapy_related_pain",
    "diarrhea",
    "hypotension",
    "vomiting",
    "infection",
    "hypersensitivity_reaction",
    "capillary_leak"
  ),
  prob_anemia = 0.42,
  prob_leukopenia = 0.45,
  prob_neutropenia = 0.33,
  prob_thrombocytopenia = 0.35,
  prob_fever = 0.18,
  prob_urticaria = 0.05,
  prob_immunotherapy_related_pain = 0.16,
  prob_diarrhea = 0.07,
  prob_hypotension = 0.08,
  prob_vomiting = 0.06,
  prob_infection = 0.25,
  prob_hypersensitivity_reaction = 0.08,
  prob_capillary_leak = 0.1,
  cost_anemia = 0,
  cost_leukopenia = 0,
  cost_neutropenia = 0,
  cost_thrombocytopenia = 0,
  cost_fever = 1.98,
  cost_urticaria = 0,
  cost_immunotherapy_related_pain = 0,
  cost_diarrhea = 3.2,
  cost_hypotension = 0,
  cost_vomiting = 8.45,
  cost_infection = 222.33,
  cost_hypersensitivity_reaction = 4.13,
  cost_capillary_leak = 307.37,
  cost_pain = 6.36,
  cost_laboratory = 141.45,
  cost_hospitalisation = 3763.62,
  Temo_unit_mg = 50,
  Temo_dose_days = 5,
  Temo_unit_price = 15.34,
  Iri_unit_mg = 40,
  Iri_dose_days = 5,
  Iri_unit_price =  4.4,
  u_EFS = 0.84,
  u_PPS = 0.56,
  df_life_table = df_life_table
)

usethis::use_data(l_psm_parameters, overwrite = TRUE)
